blank_issues_enabled: false
contact_links:
  - name: Bug ou Nova funcionalidade
    url: https://github.com/Minhacps/votacidade/issues
    about: Reporte um problema ou sugira uma nova funcionalidade
