blank_issues_enabled: false
contact_links:
  - name: Bug ou Novas funcionalidades
    url: https://github.com/Minhacps/votacidade/issues
    about: Reporte um problema ou sugira novas funcionalidades
