export const candidate = {
  age: '35-39',
  answers: [
    'DT',
    'DT',
    'DT',
    'DT',
    'DT',
    'DT',
    'C',
    'CT',
    'DT',
    'DT',
    'DT',
    'DT',
    'D',
    'DT',
    'DT',
    'DT',
    'CT',
    'DT',
    'DT',
    'D',
    'D',
    'DT',
    'D',
    'D',
    'DT',
    'D',
    'DT',
    'DT',
    'DT',
    'D',
  ],
  candidateNumber: '012345',
  city: 'campinas',
  cnpj: '11.111.111/1111-11',
  description:
    'Zu zojij catatgu fu bopolvar relcozsew ba julram ohilihup lokaer matu ceg oh esefanvi.',
  email: 'candidate@vota.org.br',
  ethnicGroup: 'ethnic group',
  gender: 'gender',
  name: 'candidate name',
  picture: 'http://vota.org.br/foto.jpg',
  politicalParty: 'ABC',
  role: 'candidate',
  socialGroup: '',
};

export const candidateAnswers = {
  0: { answer: 'DT', justification: '' },
  1: { answer: 'DT' },
  2: { answer: 'DT', justification: '' },
  3: { answer: 'DT', justification: '' },
  4: { justification: '', answer: 'DT' },
  5: { answer: 'DT', justification: '' },
  6: { answer: 'C', justification: '' },
  7: { justification: '', answer: 'CT' },
  8: { justification: '', answer: 'DT' },
  9: { justification: '', answer: 'DT' },
  10: { answer: 'DT', justification: '' },
  11: { answer: 'DT', justification: '' },
  12: { justification: '', answer: 'D' },
  13: { answer: 'DT', justification: '' },
  14: { justification: '', answer: 'DT' },
  15: { answer: 'DT', justification: '' },
  16: { justification: '', answer: 'CT' },
  17: { answer: 'DT', justification: '' },
  18: { justification: '', answer: 'DT' },
  19: { answer: 'D', justification: '' },
  20: { answer: 'D', justification: '' },
  21: { answer: 'DT', justification: '' },
  22: { answer: 'D', justification: '' },
  23: { justification: '', answer: 'D' },
  24: { answer: 'DT', justification: '' },
  25: { justification: '', answer: 'D' },
  26: { answer: 'DT', justification: '' },
  27: { answer: 'DT', justification: '' },
  28: { justification: '', answer: 'DT' },
  29: { answer: 'D', justification: '' },
};
