export default [
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture:
      'https://em.wattpad.com/b8b45008fd08719ec5b18d6ab520d4b789a47cda/68747470733a2f2f73332e616d617a6f6e6177732e636f6d2f776174747061642d6d656469612d736572766963652f53746f7279496d6167652f6d616576766349373659766162773d3d2d3233302e313466613762303363666533373861613835393732383034383836302e6a7067?s=fit&w=720&h=720',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: '',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: '',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: '',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: '',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: '',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: '',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: '',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: '',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: '',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: '',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: '',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: '',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: '',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: '',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: '',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: '',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: '',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: '',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: '',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: '',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: '',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: '',
    description: 'Descrição',
    match: 1230,
  },
];
