export default [
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: 'url',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: 'url',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: 'url',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: 'url',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: 'url',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: 'url',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: 'url',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: 'url',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: 'url',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: 'url',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: 'url',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: 'url',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: 'url',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: 'url',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: 'url',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: 'url',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: 'url',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: 'url',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: 'url',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: 'url',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: 'url',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: 'url',
    description: 'Descrição',
    match: 1230,
  },
  {
    id: 'uid',
    age: '18-24',
    gender: 'Masculino',
    socialGroup: '',
    ethnicGroup: 'Branca',
    politicalParty: 'PT',
    candidateNumber: '99999',
    name: 'John Doe',
    picture: 'url',
    description: 'Descrição',
    match: 1230,
  },
];
